CHANCES = {
	'CHANCE_OF_COAL': 0.62,
	'CHANCE_OF_IRON': 0.57,
	'CHANCE_OF_GOLD': 0.35,
	'CHANCE_OF_DIAMOND': 0.08,
	'CHANCE_OF_CREEPER': 0.01,
}

COSTS = {
	'COST_OF_COAL': 1,
	'COST_OF_IRON': 5,
	'COST_OF_GOLD': 20,
	'COST_OF_DIAMOND': 50,
}

NUMBER_OF_CHANCE = 1000